CONFIG_CAN=y
CONFIG_GPIO=y 
CONFIG_LOG=y
CONFIG_LOG_BACKEND_FORMAT_TIMESTAMP=y 
CONFIG_LOG_BACKEND_SHOW_COLOR=y 


# gets rid of copious compiler notes and macro expansions when building
CONFIG_COMPILER_OPT="-ftrack-macro-expansion=0"
