/**
 * @file hv500_can2_map_v25_sid.c
 *
 * @brief This source file was generated by cantools version 40.2.1 Tue Feb 17 10:07:09 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "hv500_can2_map_v25_sid.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int hv500_can2_map_v25_sid_hv500_erpm_duty_voltage_pack(
    uint8_t *dst_p,
    const struct hv500_can2_map_v25_sid_hv500_erpm_duty_voltage_t *src_p,
    size_t size)
{
    uint16_t actual_duty;
    uint16_t actual_input_voltage;
    uint32_t actual_erpm;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    actual_erpm = (uint32_t)src_p->actual_erpm;
    dst_p[0] |= pack_right_shift_u32(actual_erpm, 24u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(actual_erpm, 16u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(actual_erpm, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u32(actual_erpm, 0u, 0xffu);
    actual_duty = (uint16_t)src_p->actual_duty;
    dst_p[4] |= pack_right_shift_u16(actual_duty, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(actual_duty, 0u, 0xffu);
    actual_input_voltage = (uint16_t)src_p->actual_input_voltage;
    dst_p[6] |= pack_right_shift_u16(actual_input_voltage, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(actual_input_voltage, 0u, 0xffu);

    return (8);
}

int hv500_can2_map_v25_sid_hv500_erpm_duty_voltage_unpack(
    struct hv500_can2_map_v25_sid_hv500_erpm_duty_voltage_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t actual_duty;
    uint16_t actual_input_voltage;
    uint32_t actual_erpm;

    if (size < 8u) {
        return (-EINVAL);
    }

    actual_erpm = unpack_left_shift_u32(src_p[0], 24u, 0xffu);
    actual_erpm |= unpack_left_shift_u32(src_p[1], 16u, 0xffu);
    actual_erpm |= unpack_left_shift_u32(src_p[2], 8u, 0xffu);
    actual_erpm |= unpack_right_shift_u32(src_p[3], 0u, 0xffu);
    dst_p->actual_erpm = (int32_t)actual_erpm;
    actual_duty = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    actual_duty |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->actual_duty = (int16_t)actual_duty;
    actual_input_voltage = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    actual_input_voltage |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);
    dst_p->actual_input_voltage = (int16_t)actual_input_voltage;

    return (0);
}

int hv500_can2_map_v25_sid_hv500_erpm_duty_voltage_init(struct hv500_can2_map_v25_sid_hv500_erpm_duty_voltage_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct hv500_can2_map_v25_sid_hv500_erpm_duty_voltage_t));

    return 0;
}

int32_t hv500_can2_map_v25_sid_hv500_erpm_duty_voltage_actual_erpm_encode(double value)
{
    return (int32_t)(value);
}

double hv500_can2_map_v25_sid_hv500_erpm_duty_voltage_actual_erpm_decode(int32_t value)
{
    return ((double)value);
}

bool hv500_can2_map_v25_sid_hv500_erpm_duty_voltage_actual_erpm_is_in_range(int32_t value)
{
    return ((value >= -120000) && (value <= 120000));
}

int16_t hv500_can2_map_v25_sid_hv500_erpm_duty_voltage_actual_duty_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double hv500_can2_map_v25_sid_hv500_erpm_duty_voltage_actual_duty_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool hv500_can2_map_v25_sid_hv500_erpm_duty_voltage_actual_duty_is_in_range(int16_t value)
{
    return ((value >= -1000) && (value <= 1000));
}

int16_t hv500_can2_map_v25_sid_hv500_erpm_duty_voltage_actual_input_voltage_encode(double value)
{
    return (int16_t)(value);
}

double hv500_can2_map_v25_sid_hv500_erpm_duty_voltage_actual_input_voltage_decode(int16_t value)
{
    return ((double)value);
}

bool hv500_can2_map_v25_sid_hv500_erpm_duty_voltage_actual_input_voltage_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 1000));
}

int hv500_can2_map_v25_sid_hv500_ac_dc_current_pack(
    uint8_t *dst_p,
    const struct hv500_can2_map_v25_sid_hv500_ac_dc_current_t *src_p,
    size_t size)
{
    uint16_t actual_ac_current;
    uint16_t actual_dc_current;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    actual_ac_current = (uint16_t)src_p->actual_ac_current;
    dst_p[0] |= pack_right_shift_u16(actual_ac_current, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(actual_ac_current, 0u, 0xffu);
    actual_dc_current = (uint16_t)src_p->actual_dc_current;
    dst_p[2] |= pack_right_shift_u16(actual_dc_current, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(actual_dc_current, 0u, 0xffu);

    return (8);
}

int hv500_can2_map_v25_sid_hv500_ac_dc_current_unpack(
    struct hv500_can2_map_v25_sid_hv500_ac_dc_current_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t actual_ac_current;
    uint16_t actual_dc_current;

    if (size < 8u) {
        return (-EINVAL);
    }

    actual_ac_current = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    actual_ac_current |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->actual_ac_current = (int16_t)actual_ac_current;
    actual_dc_current = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    actual_dc_current |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->actual_dc_current = (int16_t)actual_dc_current;

    return (0);
}

int hv500_can2_map_v25_sid_hv500_ac_dc_current_init(struct hv500_can2_map_v25_sid_hv500_ac_dc_current_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct hv500_can2_map_v25_sid_hv500_ac_dc_current_t));

    return 0;
}

int16_t hv500_can2_map_v25_sid_hv500_ac_dc_current_actual_ac_current_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double hv500_can2_map_v25_sid_hv500_ac_dc_current_actual_ac_current_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool hv500_can2_map_v25_sid_hv500_ac_dc_current_actual_ac_current_is_in_range(int16_t value)
{
    return ((value >= -8500) && (value <= 8500));
}

int16_t hv500_can2_map_v25_sid_hv500_ac_dc_current_actual_dc_current_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double hv500_can2_map_v25_sid_hv500_ac_dc_current_actual_dc_current_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool hv500_can2_map_v25_sid_hv500_ac_dc_current_actual_dc_current_is_in_range(int16_t value)
{
    return ((value >= -8500) && (value <= 8500));
}

int hv500_can2_map_v25_sid_hv500_temperatures_pack(
    uint8_t *dst_p,
    const struct hv500_can2_map_v25_sid_hv500_temperatures_t *src_p,
    size_t size)
{
    uint16_t actual_temp_controller;
    uint16_t actual_temp_motor;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    actual_temp_controller = (uint16_t)src_p->actual_temp_controller;
    dst_p[0] |= pack_right_shift_u16(actual_temp_controller, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(actual_temp_controller, 0u, 0xffu);
    actual_temp_motor = (uint16_t)src_p->actual_temp_motor;
    dst_p[2] |= pack_right_shift_u16(actual_temp_motor, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(actual_temp_motor, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->actual_fault_code, 0u, 0xffu);

    return (8);
}

int hv500_can2_map_v25_sid_hv500_temperatures_unpack(
    struct hv500_can2_map_v25_sid_hv500_temperatures_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t actual_temp_controller;
    uint16_t actual_temp_motor;

    if (size < 8u) {
        return (-EINVAL);
    }

    actual_temp_controller = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    actual_temp_controller |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->actual_temp_controller = (int16_t)actual_temp_controller;
    actual_temp_motor = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    actual_temp_motor |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->actual_temp_motor = (int16_t)actual_temp_motor;
    dst_p->actual_fault_code = unpack_right_shift_u8(src_p[4], 0u, 0xffu);

    return (0);
}

int hv500_can2_map_v25_sid_hv500_temperatures_init(struct hv500_can2_map_v25_sid_hv500_temperatures_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct hv500_can2_map_v25_sid_hv500_temperatures_t));

    return 0;
}

int16_t hv500_can2_map_v25_sid_hv500_temperatures_actual_temp_controller_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double hv500_can2_map_v25_sid_hv500_temperatures_actual_temp_controller_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool hv500_can2_map_v25_sid_hv500_temperatures_actual_temp_controller_is_in_range(int16_t value)
{
    return ((value >= -550) && (value <= 2000));
}

int16_t hv500_can2_map_v25_sid_hv500_temperatures_actual_temp_motor_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double hv500_can2_map_v25_sid_hv500_temperatures_actual_temp_motor_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool hv500_can2_map_v25_sid_hv500_temperatures_actual_temp_motor_is_in_range(int16_t value)
{
    return ((value >= -550) && (value <= 2000));
}

uint8_t hv500_can2_map_v25_sid_hv500_temperatures_actual_fault_code_encode(double value)
{
    return (uint8_t)(value);
}

double hv500_can2_map_v25_sid_hv500_temperatures_actual_fault_code_decode(uint8_t value)
{
    return ((double)value);
}

bool hv500_can2_map_v25_sid_hv500_temperatures_actual_fault_code_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int hv500_can2_map_v25_sid_hv500_foc_pack(
    uint8_t *dst_p,
    const struct hv500_can2_map_v25_sid_hv500_foc_t *src_p,
    size_t size)
{
    uint32_t actual_foc_id;
    uint32_t actual_foc_iq;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    actual_foc_id = (uint32_t)src_p->actual_foc_id;
    dst_p[0] |= pack_right_shift_u32(actual_foc_id, 24u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(actual_foc_id, 16u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(actual_foc_id, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u32(actual_foc_id, 0u, 0xffu);
    actual_foc_iq = (uint32_t)src_p->actual_foc_iq;
    dst_p[4] |= pack_right_shift_u32(actual_foc_iq, 24u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(actual_foc_iq, 16u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(actual_foc_iq, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u32(actual_foc_iq, 0u, 0xffu);

    return (8);
}

int hv500_can2_map_v25_sid_hv500_foc_unpack(
    struct hv500_can2_map_v25_sid_hv500_foc_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t actual_foc_id;
    uint32_t actual_foc_iq;

    if (size < 8u) {
        return (-EINVAL);
    }

    actual_foc_id = unpack_left_shift_u32(src_p[0], 24u, 0xffu);
    actual_foc_id |= unpack_left_shift_u32(src_p[1], 16u, 0xffu);
    actual_foc_id |= unpack_left_shift_u32(src_p[2], 8u, 0xffu);
    actual_foc_id |= unpack_right_shift_u32(src_p[3], 0u, 0xffu);
    dst_p->actual_foc_id = (int32_t)actual_foc_id;
    actual_foc_iq = unpack_left_shift_u32(src_p[4], 24u, 0xffu);
    actual_foc_iq |= unpack_left_shift_u32(src_p[5], 16u, 0xffu);
    actual_foc_iq |= unpack_left_shift_u32(src_p[6], 8u, 0xffu);
    actual_foc_iq |= unpack_right_shift_u32(src_p[7], 0u, 0xffu);
    dst_p->actual_foc_iq = (int32_t)actual_foc_iq;

    return (0);
}

int hv500_can2_map_v25_sid_hv500_foc_init(struct hv500_can2_map_v25_sid_hv500_foc_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct hv500_can2_map_v25_sid_hv500_foc_t));

    return 0;
}

int32_t hv500_can2_map_v25_sid_hv500_foc_actual_foc_id_encode(double value)
{
    return (int32_t)(value / 0.01);
}

double hv500_can2_map_v25_sid_hv500_foc_actual_foc_id_decode(int32_t value)
{
    return ((double)value * 0.01);
}

bool hv500_can2_map_v25_sid_hv500_foc_actual_foc_id_is_in_range(int32_t value)
{
    return ((value >= -85000) && (value <= 85000));
}

int32_t hv500_can2_map_v25_sid_hv500_foc_actual_foc_iq_encode(double value)
{
    return (int32_t)(value / 0.01);
}

double hv500_can2_map_v25_sid_hv500_foc_actual_foc_iq_decode(int32_t value)
{
    return ((double)value * 0.01);
}

bool hv500_can2_map_v25_sid_hv500_foc_actual_foc_iq_is_in_range(int32_t value)
{
    return ((value >= -85000) && (value <= 85000));
}

int hv500_can2_map_v25_sid_hv500_misc_pack(
    uint8_t *dst_p,
    const struct hv500_can2_map_v25_sid_hv500_misc_t *src_p,
    size_t size)
{
    uint8_t actual_brake;
    uint8_t actual_throttle;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    actual_throttle = (uint8_t)src_p->actual_throttle;
    dst_p[0] |= pack_left_shift_u8(actual_throttle, 0u, 0xffu);
    actual_brake = (uint8_t)src_p->actual_brake;
    dst_p[1] |= pack_left_shift_u8(actual_brake, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->digital_output_4, 7u, 0x80u);
    dst_p[2] |= pack_left_shift_u8(src_p->digital_output_3, 6u, 0x40u);
    dst_p[2] |= pack_left_shift_u8(src_p->digital_output_2, 5u, 0x20u);
    dst_p[2] |= pack_left_shift_u8(src_p->digital_output_1, 4u, 0x10u);
    dst_p[2] |= pack_left_shift_u8(src_p->digital_input_4, 3u, 0x08u);
    dst_p[2] |= pack_left_shift_u8(src_p->digital_input_3, 2u, 0x04u);
    dst_p[2] |= pack_left_shift_u8(src_p->digital_input_2, 1u, 0x02u);
    dst_p[2] |= pack_left_shift_u8(src_p->digital_input_1, 0u, 0x01u);
    dst_p[3] |= pack_left_shift_u8(src_p->drive_enable, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->motor_temp_limit, 7u, 0x80u);
    dst_p[4] |= pack_left_shift_u8(src_p->motor_accel_limit, 6u, 0x40u);
    dst_p[4] |= pack_left_shift_u8(src_p->input_voltage_limit, 5u, 0x20u);
    dst_p[4] |= pack_left_shift_u8(src_p->igbt_temp_limit, 4u, 0x10u);
    dst_p[4] |= pack_left_shift_u8(src_p->igbt_accel_limit, 3u, 0x08u);
    dst_p[4] |= pack_left_shift_u8(src_p->drive_enable_limit, 2u, 0x04u);
    dst_p[4] |= pack_left_shift_u8(src_p->dc_current_limit, 1u, 0x02u);
    dst_p[4] |= pack_left_shift_u8(src_p->capacitor_temp_limit, 0u, 0x01u);
    dst_p[5] |= pack_left_shift_u8(src_p->power_limit, 2u, 0x04u);
    dst_p[5] |= pack_left_shift_u8(src_p->rpm_max_limit, 1u, 0x02u);
    dst_p[5] |= pack_left_shift_u8(src_p->rpm_min_limit, 0u, 0x01u);
    dst_p[7] |= pack_left_shift_u8(src_p->can_map_version, 0u, 0xffu);

    return (8);
}

int hv500_can2_map_v25_sid_hv500_misc_unpack(
    struct hv500_can2_map_v25_sid_hv500_misc_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t actual_brake;
    uint8_t actual_throttle;

    if (size < 8u) {
        return (-EINVAL);
    }

    actual_throttle = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->actual_throttle = (int8_t)actual_throttle;
    actual_brake = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->actual_brake = (int8_t)actual_brake;
    dst_p->digital_output_4 = unpack_right_shift_u8(src_p[2], 7u, 0x80u);
    dst_p->digital_output_3 = unpack_right_shift_u8(src_p[2], 6u, 0x40u);
    dst_p->digital_output_2 = unpack_right_shift_u8(src_p[2], 5u, 0x20u);
    dst_p->digital_output_1 = unpack_right_shift_u8(src_p[2], 4u, 0x10u);
    dst_p->digital_input_4 = unpack_right_shift_u8(src_p[2], 3u, 0x08u);
    dst_p->digital_input_3 = unpack_right_shift_u8(src_p[2], 2u, 0x04u);
    dst_p->digital_input_2 = unpack_right_shift_u8(src_p[2], 1u, 0x02u);
    dst_p->digital_input_1 = unpack_right_shift_u8(src_p[2], 0u, 0x01u);
    dst_p->drive_enable = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->motor_temp_limit = unpack_right_shift_u8(src_p[4], 7u, 0x80u);
    dst_p->motor_accel_limit = unpack_right_shift_u8(src_p[4], 6u, 0x40u);
    dst_p->input_voltage_limit = unpack_right_shift_u8(src_p[4], 5u, 0x20u);
    dst_p->igbt_temp_limit = unpack_right_shift_u8(src_p[4], 4u, 0x10u);
    dst_p->igbt_accel_limit = unpack_right_shift_u8(src_p[4], 3u, 0x08u);
    dst_p->drive_enable_limit = unpack_right_shift_u8(src_p[4], 2u, 0x04u);
    dst_p->dc_current_limit = unpack_right_shift_u8(src_p[4], 1u, 0x02u);
    dst_p->capacitor_temp_limit = unpack_right_shift_u8(src_p[4], 0u, 0x01u);
    dst_p->power_limit = unpack_right_shift_u8(src_p[5], 2u, 0x04u);
    dst_p->rpm_max_limit = unpack_right_shift_u8(src_p[5], 1u, 0x02u);
    dst_p->rpm_min_limit = unpack_right_shift_u8(src_p[5], 0u, 0x01u);
    dst_p->can_map_version = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int hv500_can2_map_v25_sid_hv500_misc_init(struct hv500_can2_map_v25_sid_hv500_misc_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct hv500_can2_map_v25_sid_hv500_misc_t));

    return 0;
}

int8_t hv500_can2_map_v25_sid_hv500_misc_actual_throttle_encode(double value)
{
    return (int8_t)(value);
}

double hv500_can2_map_v25_sid_hv500_misc_actual_throttle_decode(int8_t value)
{
    return ((double)value);
}

bool hv500_can2_map_v25_sid_hv500_misc_actual_throttle_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 100));
}

int8_t hv500_can2_map_v25_sid_hv500_misc_actual_brake_encode(double value)
{
    return (int8_t)(value);
}

double hv500_can2_map_v25_sid_hv500_misc_actual_brake_decode(int8_t value)
{
    return ((double)value);
}

bool hv500_can2_map_v25_sid_hv500_misc_actual_brake_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 100));
}

uint8_t hv500_can2_map_v25_sid_hv500_misc_digital_output_4_encode(double value)
{
    return (uint8_t)(value);
}

double hv500_can2_map_v25_sid_hv500_misc_digital_output_4_decode(uint8_t value)
{
    return ((double)value);
}

bool hv500_can2_map_v25_sid_hv500_misc_digital_output_4_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t hv500_can2_map_v25_sid_hv500_misc_digital_output_3_encode(double value)
{
    return (uint8_t)(value);
}

double hv500_can2_map_v25_sid_hv500_misc_digital_output_3_decode(uint8_t value)
{
    return ((double)value);
}

bool hv500_can2_map_v25_sid_hv500_misc_digital_output_3_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t hv500_can2_map_v25_sid_hv500_misc_digital_output_2_encode(double value)
{
    return (uint8_t)(value);
}

double hv500_can2_map_v25_sid_hv500_misc_digital_output_2_decode(uint8_t value)
{
    return ((double)value);
}

bool hv500_can2_map_v25_sid_hv500_misc_digital_output_2_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t hv500_can2_map_v25_sid_hv500_misc_digital_output_1_encode(double value)
{
    return (uint8_t)(value);
}

double hv500_can2_map_v25_sid_hv500_misc_digital_output_1_decode(uint8_t value)
{
    return ((double)value);
}

bool hv500_can2_map_v25_sid_hv500_misc_digital_output_1_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t hv500_can2_map_v25_sid_hv500_misc_digital_input_4_encode(double value)
{
    return (uint8_t)(value);
}

double hv500_can2_map_v25_sid_hv500_misc_digital_input_4_decode(uint8_t value)
{
    return ((double)value);
}

bool hv500_can2_map_v25_sid_hv500_misc_digital_input_4_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t hv500_can2_map_v25_sid_hv500_misc_digital_input_3_encode(double value)
{
    return (uint8_t)(value);
}

double hv500_can2_map_v25_sid_hv500_misc_digital_input_3_decode(uint8_t value)
{
    return ((double)value);
}

bool hv500_can2_map_v25_sid_hv500_misc_digital_input_3_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t hv500_can2_map_v25_sid_hv500_misc_digital_input_2_encode(double value)
{
    return (uint8_t)(value);
}

double hv500_can2_map_v25_sid_hv500_misc_digital_input_2_decode(uint8_t value)
{
    return ((double)value);
}

bool hv500_can2_map_v25_sid_hv500_misc_digital_input_2_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t hv500_can2_map_v25_sid_hv500_misc_digital_input_1_encode(double value)
{
    return (uint8_t)(value);
}

double hv500_can2_map_v25_sid_hv500_misc_digital_input_1_decode(uint8_t value)
{
    return ((double)value);
}

bool hv500_can2_map_v25_sid_hv500_misc_digital_input_1_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t hv500_can2_map_v25_sid_hv500_misc_drive_enable_encode(double value)
{
    return (uint8_t)(value);
}

double hv500_can2_map_v25_sid_hv500_misc_drive_enable_decode(uint8_t value)
{
    return ((double)value);
}

bool hv500_can2_map_v25_sid_hv500_misc_drive_enable_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t hv500_can2_map_v25_sid_hv500_misc_motor_temp_limit_encode(double value)
{
    return (uint8_t)(value);
}

double hv500_can2_map_v25_sid_hv500_misc_motor_temp_limit_decode(uint8_t value)
{
    return ((double)value);
}

bool hv500_can2_map_v25_sid_hv500_misc_motor_temp_limit_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t hv500_can2_map_v25_sid_hv500_misc_motor_accel_limit_encode(double value)
{
    return (uint8_t)(value);
}

double hv500_can2_map_v25_sid_hv500_misc_motor_accel_limit_decode(uint8_t value)
{
    return ((double)value);
}

bool hv500_can2_map_v25_sid_hv500_misc_motor_accel_limit_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t hv500_can2_map_v25_sid_hv500_misc_input_voltage_limit_encode(double value)
{
    return (uint8_t)(value);
}

double hv500_can2_map_v25_sid_hv500_misc_input_voltage_limit_decode(uint8_t value)
{
    return ((double)value);
}

bool hv500_can2_map_v25_sid_hv500_misc_input_voltage_limit_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t hv500_can2_map_v25_sid_hv500_misc_igbt_temp_limit_encode(double value)
{
    return (uint8_t)(value);
}

double hv500_can2_map_v25_sid_hv500_misc_igbt_temp_limit_decode(uint8_t value)
{
    return ((double)value);
}

bool hv500_can2_map_v25_sid_hv500_misc_igbt_temp_limit_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t hv500_can2_map_v25_sid_hv500_misc_igbt_accel_limit_encode(double value)
{
    return (uint8_t)(value);
}

double hv500_can2_map_v25_sid_hv500_misc_igbt_accel_limit_decode(uint8_t value)
{
    return ((double)value);
}

bool hv500_can2_map_v25_sid_hv500_misc_igbt_accel_limit_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t hv500_can2_map_v25_sid_hv500_misc_drive_enable_limit_encode(double value)
{
    return (uint8_t)(value);
}

double hv500_can2_map_v25_sid_hv500_misc_drive_enable_limit_decode(uint8_t value)
{
    return ((double)value);
}

bool hv500_can2_map_v25_sid_hv500_misc_drive_enable_limit_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t hv500_can2_map_v25_sid_hv500_misc_dc_current_limit_encode(double value)
{
    return (uint8_t)(value);
}

double hv500_can2_map_v25_sid_hv500_misc_dc_current_limit_decode(uint8_t value)
{
    return ((double)value);
}

bool hv500_can2_map_v25_sid_hv500_misc_dc_current_limit_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t hv500_can2_map_v25_sid_hv500_misc_capacitor_temp_limit_encode(double value)
{
    return (uint8_t)(value);
}

double hv500_can2_map_v25_sid_hv500_misc_capacitor_temp_limit_decode(uint8_t value)
{
    return ((double)value);
}

bool hv500_can2_map_v25_sid_hv500_misc_capacitor_temp_limit_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t hv500_can2_map_v25_sid_hv500_misc_power_limit_encode(double value)
{
    return (uint8_t)(value);
}

double hv500_can2_map_v25_sid_hv500_misc_power_limit_decode(uint8_t value)
{
    return ((double)value);
}

bool hv500_can2_map_v25_sid_hv500_misc_power_limit_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t hv500_can2_map_v25_sid_hv500_misc_rpm_max_limit_encode(double value)
{
    return (uint8_t)(value);
}

double hv500_can2_map_v25_sid_hv500_misc_rpm_max_limit_decode(uint8_t value)
{
    return ((double)value);
}

bool hv500_can2_map_v25_sid_hv500_misc_rpm_max_limit_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t hv500_can2_map_v25_sid_hv500_misc_rpm_min_limit_encode(double value)
{
    return (uint8_t)(value);
}

double hv500_can2_map_v25_sid_hv500_misc_rpm_min_limit_decode(uint8_t value)
{
    return ((double)value);
}

bool hv500_can2_map_v25_sid_hv500_misc_rpm_min_limit_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t hv500_can2_map_v25_sid_hv500_misc_can_map_version_encode(double value)
{
    return (uint8_t)(value / 0.1);
}

double hv500_can2_map_v25_sid_hv500_misc_can_map_version_decode(uint8_t value)
{
    return ((double)value * 0.1);
}

bool hv500_can2_map_v25_sid_hv500_misc_can_map_version_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int hv500_can2_map_v25_sid_hv500_set_drive_enable_pack(
    uint8_t *dst_p,
    const struct hv500_can2_map_v25_sid_hv500_set_drive_enable_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u8(src_p->cmd_drive_enable, 0u, 0xffu);

    return (2);
}

int hv500_can2_map_v25_sid_hv500_set_drive_enable_unpack(
    struct hv500_can2_map_v25_sid_hv500_set_drive_enable_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->cmd_drive_enable = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int hv500_can2_map_v25_sid_hv500_set_drive_enable_init(struct hv500_can2_map_v25_sid_hv500_set_drive_enable_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct hv500_can2_map_v25_sid_hv500_set_drive_enable_t));

    return 0;
}

uint8_t hv500_can2_map_v25_sid_hv500_set_drive_enable_cmd_drive_enable_encode(double value)
{
    return (uint8_t)(value);
}

double hv500_can2_map_v25_sid_hv500_set_drive_enable_cmd_drive_enable_decode(uint8_t value)
{
    return ((double)value);
}

bool hv500_can2_map_v25_sid_hv500_set_drive_enable_cmd_drive_enable_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int hv500_can2_map_v25_sid_hv500_set_ac_current_pack(
    uint8_t *dst_p,
    const struct hv500_can2_map_v25_sid_hv500_set_ac_current_t *src_p,
    size_t size)
{
    uint16_t cmd_target_ac_current;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    cmd_target_ac_current = (uint16_t)src_p->cmd_target_ac_current;
    dst_p[0] |= pack_right_shift_u16(cmd_target_ac_current, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(cmd_target_ac_current, 0u, 0xffu);

    return (8);
}

int hv500_can2_map_v25_sid_hv500_set_ac_current_unpack(
    struct hv500_can2_map_v25_sid_hv500_set_ac_current_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t cmd_target_ac_current;

    if (size < 8u) {
        return (-EINVAL);
    }

    cmd_target_ac_current = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    cmd_target_ac_current |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->cmd_target_ac_current = (int16_t)cmd_target_ac_current;

    return (0);
}

int hv500_can2_map_v25_sid_hv500_set_ac_current_init(struct hv500_can2_map_v25_sid_hv500_set_ac_current_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct hv500_can2_map_v25_sid_hv500_set_ac_current_t));

    return 0;
}

int16_t hv500_can2_map_v25_sid_hv500_set_ac_current_cmd_target_ac_current_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double hv500_can2_map_v25_sid_hv500_set_ac_current_cmd_target_ac_current_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool hv500_can2_map_v25_sid_hv500_set_ac_current_cmd_target_ac_current_is_in_range(int16_t value)
{
    return ((value >= -8500) && (value <= 8500));
}

int hv500_can2_map_v25_sid_hv500_set_brake_current_pack(
    uint8_t *dst_p,
    const struct hv500_can2_map_v25_sid_hv500_set_brake_current_t *src_p,
    size_t size)
{
    uint16_t cmd_target_brake_current;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    cmd_target_brake_current = (uint16_t)src_p->cmd_target_brake_current;
    dst_p[0] |= pack_right_shift_u16(cmd_target_brake_current, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(cmd_target_brake_current, 0u, 0xffu);

    return (8);
}

int hv500_can2_map_v25_sid_hv500_set_brake_current_unpack(
    struct hv500_can2_map_v25_sid_hv500_set_brake_current_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t cmd_target_brake_current;

    if (size < 8u) {
        return (-EINVAL);
    }

    cmd_target_brake_current = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    cmd_target_brake_current |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->cmd_target_brake_current = (int16_t)cmd_target_brake_current;

    return (0);
}

int hv500_can2_map_v25_sid_hv500_set_brake_current_init(struct hv500_can2_map_v25_sid_hv500_set_brake_current_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct hv500_can2_map_v25_sid_hv500_set_brake_current_t));

    return 0;
}

int16_t hv500_can2_map_v25_sid_hv500_set_brake_current_cmd_target_brake_current_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double hv500_can2_map_v25_sid_hv500_set_brake_current_cmd_target_brake_current_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool hv500_can2_map_v25_sid_hv500_set_brake_current_cmd_target_brake_current_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 8500));
}

int hv500_can2_map_v25_sid_hv500_set_erpm_pack(
    uint8_t *dst_p,
    const struct hv500_can2_map_v25_sid_hv500_set_erpm_t *src_p,
    size_t size)
{
    uint32_t cmd_target_speed;

    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    cmd_target_speed = (uint32_t)src_p->cmd_target_speed;
    dst_p[0] |= pack_right_shift_u32(cmd_target_speed, 24u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(cmd_target_speed, 16u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(cmd_target_speed, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u32(cmd_target_speed, 0u, 0xffu);

    return (4);
}

int hv500_can2_map_v25_sid_hv500_set_erpm_unpack(
    struct hv500_can2_map_v25_sid_hv500_set_erpm_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t cmd_target_speed;

    if (size < 4u) {
        return (-EINVAL);
    }

    cmd_target_speed = unpack_left_shift_u32(src_p[0], 24u, 0xffu);
    cmd_target_speed |= unpack_left_shift_u32(src_p[1], 16u, 0xffu);
    cmd_target_speed |= unpack_left_shift_u32(src_p[2], 8u, 0xffu);
    cmd_target_speed |= unpack_right_shift_u32(src_p[3], 0u, 0xffu);
    dst_p->cmd_target_speed = (int32_t)cmd_target_speed;

    return (0);
}

int hv500_can2_map_v25_sid_hv500_set_erpm_init(struct hv500_can2_map_v25_sid_hv500_set_erpm_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct hv500_can2_map_v25_sid_hv500_set_erpm_t));

    return 0;
}

int32_t hv500_can2_map_v25_sid_hv500_set_erpm_cmd_target_speed_encode(double value)
{
    return (int32_t)(value);
}

double hv500_can2_map_v25_sid_hv500_set_erpm_cmd_target_speed_decode(int32_t value)
{
    return ((double)value);
}

bool hv500_can2_map_v25_sid_hv500_set_erpm_cmd_target_speed_is_in_range(int32_t value)
{
    return ((value >= -100000) && (value <= 100000));
}

int hv500_can2_map_v25_sid_hv500_set_position_pack(
    uint8_t *dst_p,
    const struct hv500_can2_map_v25_sid_hv500_set_position_t *src_p,
    size_t size)
{
    uint16_t cmd_target_position;

    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    cmd_target_position = (uint16_t)src_p->cmd_target_position;
    dst_p[0] |= pack_right_shift_u16(cmd_target_position, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(cmd_target_position, 0u, 0xffu);

    return (2);
}

int hv500_can2_map_v25_sid_hv500_set_position_unpack(
    struct hv500_can2_map_v25_sid_hv500_set_position_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t cmd_target_position;

    if (size < 2u) {
        return (-EINVAL);
    }

    cmd_target_position = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    cmd_target_position |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->cmd_target_position = (int16_t)cmd_target_position;

    return (0);
}

int hv500_can2_map_v25_sid_hv500_set_position_init(struct hv500_can2_map_v25_sid_hv500_set_position_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct hv500_can2_map_v25_sid_hv500_set_position_t));

    return 0;
}

int16_t hv500_can2_map_v25_sid_hv500_set_position_cmd_target_position_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double hv500_can2_map_v25_sid_hv500_set_position_cmd_target_position_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool hv500_can2_map_v25_sid_hv500_set_position_cmd_target_position_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 3590));
}

int hv500_can2_map_v25_sid_hv500_set_rel_current_pack(
    uint8_t *dst_p,
    const struct hv500_can2_map_v25_sid_hv500_set_rel_current_t *src_p,
    size_t size)
{
    uint16_t cmd_target_relative_current;

    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    cmd_target_relative_current = (uint16_t)src_p->cmd_target_relative_current;
    dst_p[0] |= pack_right_shift_u16(cmd_target_relative_current, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(cmd_target_relative_current, 0u, 0xffu);

    return (2);
}

int hv500_can2_map_v25_sid_hv500_set_rel_current_unpack(
    struct hv500_can2_map_v25_sid_hv500_set_rel_current_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t cmd_target_relative_current;

    if (size < 2u) {
        return (-EINVAL);
    }

    cmd_target_relative_current = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    cmd_target_relative_current |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->cmd_target_relative_current = (int16_t)cmd_target_relative_current;

    return (0);
}

int hv500_can2_map_v25_sid_hv500_set_rel_current_init(struct hv500_can2_map_v25_sid_hv500_set_rel_current_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct hv500_can2_map_v25_sid_hv500_set_rel_current_t));

    return 0;
}

int16_t hv500_can2_map_v25_sid_hv500_set_rel_current_cmd_target_relative_current_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double hv500_can2_map_v25_sid_hv500_set_rel_current_cmd_target_relative_current_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool hv500_can2_map_v25_sid_hv500_set_rel_current_cmd_target_relative_current_is_in_range(int16_t value)
{
    return ((value >= -1000) && (value <= 1000));
}

int hv500_can2_map_v25_sid_hv500_set_rel_brake_current_pack(
    uint8_t *dst_p,
    const struct hv500_can2_map_v25_sid_hv500_set_rel_brake_current_t *src_p,
    size_t size)
{
    uint16_t cmd_targe_relative_brake_current;

    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    cmd_targe_relative_brake_current = (uint16_t)src_p->cmd_targe_relative_brake_current;
    dst_p[0] |= pack_right_shift_u16(cmd_targe_relative_brake_current, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(cmd_targe_relative_brake_current, 0u, 0xffu);

    return (2);
}

int hv500_can2_map_v25_sid_hv500_set_rel_brake_current_unpack(
    struct hv500_can2_map_v25_sid_hv500_set_rel_brake_current_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t cmd_targe_relative_brake_current;

    if (size < 2u) {
        return (-EINVAL);
    }

    cmd_targe_relative_brake_current = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    cmd_targe_relative_brake_current |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->cmd_targe_relative_brake_current = (int16_t)cmd_targe_relative_brake_current;

    return (0);
}

int hv500_can2_map_v25_sid_hv500_set_rel_brake_current_init(struct hv500_can2_map_v25_sid_hv500_set_rel_brake_current_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct hv500_can2_map_v25_sid_hv500_set_rel_brake_current_t));

    return 0;
}

int16_t hv500_can2_map_v25_sid_hv500_set_rel_brake_current_cmd_targe_relative_brake_current_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double hv500_can2_map_v25_sid_hv500_set_rel_brake_current_cmd_targe_relative_brake_current_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool hv500_can2_map_v25_sid_hv500_set_rel_brake_current_cmd_targe_relative_brake_current_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 1000));
}

int hv500_can2_map_v25_sid_hv500_set_max_ac_current_pack(
    uint8_t *dst_p,
    const struct hv500_can2_map_v25_sid_hv500_set_max_ac_current_t *src_p,
    size_t size)
{
    uint16_t cmd_max_ac_current;

    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    cmd_max_ac_current = (uint16_t)src_p->cmd_max_ac_current;
    dst_p[0] |= pack_right_shift_u16(cmd_max_ac_current, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(cmd_max_ac_current, 0u, 0xffu);

    return (2);
}

int hv500_can2_map_v25_sid_hv500_set_max_ac_current_unpack(
    struct hv500_can2_map_v25_sid_hv500_set_max_ac_current_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t cmd_max_ac_current;

    if (size < 2u) {
        return (-EINVAL);
    }

    cmd_max_ac_current = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    cmd_max_ac_current |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->cmd_max_ac_current = (int16_t)cmd_max_ac_current;

    return (0);
}

int hv500_can2_map_v25_sid_hv500_set_max_ac_current_init(struct hv500_can2_map_v25_sid_hv500_set_max_ac_current_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct hv500_can2_map_v25_sid_hv500_set_max_ac_current_t));

    return 0;
}

int16_t hv500_can2_map_v25_sid_hv500_set_max_ac_current_cmd_max_ac_current_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double hv500_can2_map_v25_sid_hv500_set_max_ac_current_cmd_max_ac_current_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool hv500_can2_map_v25_sid_hv500_set_max_ac_current_cmd_max_ac_current_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 8500));
}

int hv500_can2_map_v25_sid_hv500_set_max_ac_brake_current_pack(
    uint8_t *dst_p,
    const struct hv500_can2_map_v25_sid_hv500_set_max_ac_brake_current_t *src_p,
    size_t size)
{
    uint16_t cmd_max_ac_brake_current;

    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    cmd_max_ac_brake_current = (uint16_t)src_p->cmd_max_ac_brake_current;
    dst_p[0] |= pack_right_shift_u16(cmd_max_ac_brake_current, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(cmd_max_ac_brake_current, 0u, 0xffu);

    return (2);
}

int hv500_can2_map_v25_sid_hv500_set_max_ac_brake_current_unpack(
    struct hv500_can2_map_v25_sid_hv500_set_max_ac_brake_current_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t cmd_max_ac_brake_current;

    if (size < 2u) {
        return (-EINVAL);
    }

    cmd_max_ac_brake_current = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    cmd_max_ac_brake_current |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->cmd_max_ac_brake_current = (int16_t)cmd_max_ac_brake_current;

    return (0);
}

int hv500_can2_map_v25_sid_hv500_set_max_ac_brake_current_init(struct hv500_can2_map_v25_sid_hv500_set_max_ac_brake_current_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct hv500_can2_map_v25_sid_hv500_set_max_ac_brake_current_t));

    return 0;
}

int16_t hv500_can2_map_v25_sid_hv500_set_max_ac_brake_current_cmd_max_ac_brake_current_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double hv500_can2_map_v25_sid_hv500_set_max_ac_brake_current_cmd_max_ac_brake_current_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool hv500_can2_map_v25_sid_hv500_set_max_ac_brake_current_cmd_max_ac_brake_current_is_in_range(int16_t value)
{
    return ((value >= -8500) && (value <= 0));
}

int hv500_can2_map_v25_sid_hv500_set_max_dc_current_pack(
    uint8_t *dst_p,
    const struct hv500_can2_map_v25_sid_hv500_set_max_dc_current_t *src_p,
    size_t size)
{
    uint16_t cmd_max_dc_current;

    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    cmd_max_dc_current = (uint16_t)src_p->cmd_max_dc_current;
    dst_p[0] |= pack_right_shift_u16(cmd_max_dc_current, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(cmd_max_dc_current, 0u, 0xffu);

    return (2);
}

int hv500_can2_map_v25_sid_hv500_set_max_dc_current_unpack(
    struct hv500_can2_map_v25_sid_hv500_set_max_dc_current_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t cmd_max_dc_current;

    if (size < 2u) {
        return (-EINVAL);
    }

    cmd_max_dc_current = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    cmd_max_dc_current |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->cmd_max_dc_current = (int16_t)cmd_max_dc_current;

    return (0);
}

int hv500_can2_map_v25_sid_hv500_set_max_dc_current_init(struct hv500_can2_map_v25_sid_hv500_set_max_dc_current_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct hv500_can2_map_v25_sid_hv500_set_max_dc_current_t));

    return 0;
}

int16_t hv500_can2_map_v25_sid_hv500_set_max_dc_current_cmd_max_dc_current_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double hv500_can2_map_v25_sid_hv500_set_max_dc_current_cmd_max_dc_current_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool hv500_can2_map_v25_sid_hv500_set_max_dc_current_cmd_max_dc_current_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 8500));
}

int hv500_can2_map_v25_sid_hv500_set_max_dc_brake_current_pack(
    uint8_t *dst_p,
    const struct hv500_can2_map_v25_sid_hv500_set_max_dc_brake_current_t *src_p,
    size_t size)
{
    uint16_t cmd_max_dc_brake_current;

    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    cmd_max_dc_brake_current = (uint16_t)src_p->cmd_max_dc_brake_current;
    dst_p[0] |= pack_right_shift_u16(cmd_max_dc_brake_current, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(cmd_max_dc_brake_current, 0u, 0xffu);

    return (2);
}

int hv500_can2_map_v25_sid_hv500_set_max_dc_brake_current_unpack(
    struct hv500_can2_map_v25_sid_hv500_set_max_dc_brake_current_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t cmd_max_dc_brake_current;

    if (size < 2u) {
        return (-EINVAL);
    }

    cmd_max_dc_brake_current = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    cmd_max_dc_brake_current |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->cmd_max_dc_brake_current = (int16_t)cmd_max_dc_brake_current;

    return (0);
}

int hv500_can2_map_v25_sid_hv500_set_max_dc_brake_current_init(struct hv500_can2_map_v25_sid_hv500_set_max_dc_brake_current_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct hv500_can2_map_v25_sid_hv500_set_max_dc_brake_current_t));

    return 0;
}

int16_t hv500_can2_map_v25_sid_hv500_set_max_dc_brake_current_cmd_max_dc_brake_current_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double hv500_can2_map_v25_sid_hv500_set_max_dc_brake_current_cmd_max_dc_brake_current_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool hv500_can2_map_v25_sid_hv500_set_max_dc_brake_current_cmd_max_dc_brake_current_is_in_range(int16_t value)
{
    return ((value >= -8500) && (value <= 0));
}

int hv500_can2_map_v25_sid_hv500_set_dig_output_pack(
    uint8_t *dst_p,
    const struct hv500_can2_map_v25_sid_hv500_set_dig_output_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->cmd_set_dig_output4, 3u, 0x08u);
    dst_p[0] |= pack_left_shift_u8(src_p->cmd_set_dig_output3, 2u, 0x04u);
    dst_p[0] |= pack_left_shift_u8(src_p->cmd_set_dig_output2, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->cmd_set_dig_output1, 0u, 0x01u);

    return (8);
}

int hv500_can2_map_v25_sid_hv500_set_dig_output_unpack(
    struct hv500_can2_map_v25_sid_hv500_set_dig_output_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->cmd_set_dig_output4 = unpack_right_shift_u8(src_p[0], 3u, 0x08u);
    dst_p->cmd_set_dig_output3 = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
    dst_p->cmd_set_dig_output2 = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->cmd_set_dig_output1 = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    return (0);
}

int hv500_can2_map_v25_sid_hv500_set_dig_output_init(struct hv500_can2_map_v25_sid_hv500_set_dig_output_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct hv500_can2_map_v25_sid_hv500_set_dig_output_t));

    return 0;
}

uint8_t hv500_can2_map_v25_sid_hv500_set_dig_output_cmd_set_dig_output4_encode(double value)
{
    return (uint8_t)(value);
}

double hv500_can2_map_v25_sid_hv500_set_dig_output_cmd_set_dig_output4_decode(uint8_t value)
{
    return ((double)value);
}

bool hv500_can2_map_v25_sid_hv500_set_dig_output_cmd_set_dig_output4_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t hv500_can2_map_v25_sid_hv500_set_dig_output_cmd_set_dig_output3_encode(double value)
{
    return (uint8_t)(value);
}

double hv500_can2_map_v25_sid_hv500_set_dig_output_cmd_set_dig_output3_decode(uint8_t value)
{
    return ((double)value);
}

bool hv500_can2_map_v25_sid_hv500_set_dig_output_cmd_set_dig_output3_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t hv500_can2_map_v25_sid_hv500_set_dig_output_cmd_set_dig_output2_encode(double value)
{
    return (uint8_t)(value);
}

double hv500_can2_map_v25_sid_hv500_set_dig_output_cmd_set_dig_output2_decode(uint8_t value)
{
    return ((double)value);
}

bool hv500_can2_map_v25_sid_hv500_set_dig_output_cmd_set_dig_output2_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t hv500_can2_map_v25_sid_hv500_set_dig_output_cmd_set_dig_output1_encode(double value)
{
    return (uint8_t)(value);
}

double hv500_can2_map_v25_sid_hv500_set_dig_output_cmd_set_dig_output1_decode(uint8_t value)
{
    return ((double)value);
}

bool hv500_can2_map_v25_sid_hv500_set_dig_output_cmd_set_dig_output1_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int hv500_can2_map_v25_sid_hv500_target_iq_pack(
    uint8_t *dst_p,
    const struct hv500_can2_map_v25_sid_hv500_target_iq_t *src_p,
    size_t size)
{
    uint16_t target_iq;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->control_mode, 0u, 0xffu);
    target_iq = (uint16_t)src_p->target_iq;
    dst_p[1] |= pack_right_shift_u16(target_iq, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(target_iq, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->motor_position, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->motor_position, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->is_motor_still, 0u, 0xffu);

    return (8);
}

int hv500_can2_map_v25_sid_hv500_target_iq_unpack(
    struct hv500_can2_map_v25_sid_hv500_target_iq_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t target_iq;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->control_mode = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    target_iq = unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    target_iq |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->target_iq = (int16_t)target_iq;
    dst_p->motor_position = unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->motor_position |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->is_motor_still = unpack_right_shift_u8(src_p[5], 0u, 0xffu);

    return (0);
}

int hv500_can2_map_v25_sid_hv500_target_iq_init(struct hv500_can2_map_v25_sid_hv500_target_iq_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct hv500_can2_map_v25_sid_hv500_target_iq_t));

    return 0;
}

uint8_t hv500_can2_map_v25_sid_hv500_target_iq_control_mode_encode(double value)
{
    return (uint8_t)(value);
}

double hv500_can2_map_v25_sid_hv500_target_iq_control_mode_decode(uint8_t value)
{
    return ((double)value);
}

bool hv500_can2_map_v25_sid_hv500_target_iq_control_mode_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

int16_t hv500_can2_map_v25_sid_hv500_target_iq_target_iq_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double hv500_can2_map_v25_sid_hv500_target_iq_target_iq_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool hv500_can2_map_v25_sid_hv500_target_iq_target_iq_is_in_range(int16_t value)
{
    return ((value >= -8500) && (value <= 8500));
}

uint16_t hv500_can2_map_v25_sid_hv500_target_iq_motor_position_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double hv500_can2_map_v25_sid_hv500_target_iq_motor_position_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool hv500_can2_map_v25_sid_hv500_target_iq_motor_position_is_in_range(uint16_t value)
{
    return (value <= 3590u);
}

uint8_t hv500_can2_map_v25_sid_hv500_target_iq_is_motor_still_encode(double value)
{
    return (uint8_t)(value);
}

double hv500_can2_map_v25_sid_hv500_target_iq_is_motor_still_decode(uint8_t value)
{
    return ((double)value);
}

bool hv500_can2_map_v25_sid_hv500_target_iq_is_motor_still_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int hv500_can2_map_v25_sid_hv500_min_max_ac_current_pack(
    uint8_t *dst_p,
    const struct hv500_can2_map_v25_sid_hv500_min_max_ac_current_t *src_p,
    size_t size)
{
    uint16_t available_max_ac_current;
    uint16_t available_min_ac_current;
    uint16_t max_ac_current;
    uint16_t min_ac_current;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    max_ac_current = (uint16_t)src_p->max_ac_current;
    dst_p[0] |= pack_right_shift_u16(max_ac_current, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(max_ac_current, 0u, 0xffu);
    available_max_ac_current = (uint16_t)src_p->available_max_ac_current;
    dst_p[2] |= pack_right_shift_u16(available_max_ac_current, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(available_max_ac_current, 0u, 0xffu);
    min_ac_current = (uint16_t)src_p->min_ac_current;
    dst_p[4] |= pack_right_shift_u16(min_ac_current, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(min_ac_current, 0u, 0xffu);
    available_min_ac_current = (uint16_t)src_p->available_min_ac_current;
    dst_p[6] |= pack_right_shift_u16(available_min_ac_current, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(available_min_ac_current, 0u, 0xffu);

    return (8);
}

int hv500_can2_map_v25_sid_hv500_min_max_ac_current_unpack(
    struct hv500_can2_map_v25_sid_hv500_min_max_ac_current_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t available_max_ac_current;
    uint16_t available_min_ac_current;
    uint16_t max_ac_current;
    uint16_t min_ac_current;

    if (size < 8u) {
        return (-EINVAL);
    }

    max_ac_current = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    max_ac_current |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->max_ac_current = (int16_t)max_ac_current;
    available_max_ac_current = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    available_max_ac_current |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->available_max_ac_current = (int16_t)available_max_ac_current;
    min_ac_current = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    min_ac_current |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->min_ac_current = (int16_t)min_ac_current;
    available_min_ac_current = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    available_min_ac_current |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);
    dst_p->available_min_ac_current = (int16_t)available_min_ac_current;

    return (0);
}

int hv500_can2_map_v25_sid_hv500_min_max_ac_current_init(struct hv500_can2_map_v25_sid_hv500_min_max_ac_current_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct hv500_can2_map_v25_sid_hv500_min_max_ac_current_t));

    return 0;
}

int16_t hv500_can2_map_v25_sid_hv500_min_max_ac_current_max_ac_current_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double hv500_can2_map_v25_sid_hv500_min_max_ac_current_max_ac_current_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool hv500_can2_map_v25_sid_hv500_min_max_ac_current_max_ac_current_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 8500));
}

int16_t hv500_can2_map_v25_sid_hv500_min_max_ac_current_available_max_ac_current_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double hv500_can2_map_v25_sid_hv500_min_max_ac_current_available_max_ac_current_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool hv500_can2_map_v25_sid_hv500_min_max_ac_current_available_max_ac_current_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 8500));
}

int16_t hv500_can2_map_v25_sid_hv500_min_max_ac_current_min_ac_current_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double hv500_can2_map_v25_sid_hv500_min_max_ac_current_min_ac_current_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool hv500_can2_map_v25_sid_hv500_min_max_ac_current_min_ac_current_is_in_range(int16_t value)
{
    return ((value >= -8500) && (value <= 0));
}

int16_t hv500_can2_map_v25_sid_hv500_min_max_ac_current_available_min_ac_current_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double hv500_can2_map_v25_sid_hv500_min_max_ac_current_available_min_ac_current_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool hv500_can2_map_v25_sid_hv500_min_max_ac_current_available_min_ac_current_is_in_range(int16_t value)
{
    return ((value >= -8500) && (value <= 0));
}

int hv500_can2_map_v25_sid_hv500_min_max_dc_current_pack(
    uint8_t *dst_p,
    const struct hv500_can2_map_v25_sid_hv500_min_max_dc_current_t *src_p,
    size_t size)
{
    uint16_t available_max_dc_current;
    uint16_t available_min_dc_current;
    uint16_t max_dc_current;
    uint16_t min_dc_current;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    max_dc_current = (uint16_t)src_p->max_dc_current;
    dst_p[0] |= pack_right_shift_u16(max_dc_current, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(max_dc_current, 0u, 0xffu);
    available_max_dc_current = (uint16_t)src_p->available_max_dc_current;
    dst_p[2] |= pack_right_shift_u16(available_max_dc_current, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(available_max_dc_current, 0u, 0xffu);
    min_dc_current = (uint16_t)src_p->min_dc_current;
    dst_p[4] |= pack_right_shift_u16(min_dc_current, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(min_dc_current, 0u, 0xffu);
    available_min_dc_current = (uint16_t)src_p->available_min_dc_current;
    dst_p[6] |= pack_right_shift_u16(available_min_dc_current, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(available_min_dc_current, 0u, 0xffu);

    return (8);
}

int hv500_can2_map_v25_sid_hv500_min_max_dc_current_unpack(
    struct hv500_can2_map_v25_sid_hv500_min_max_dc_current_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t available_max_dc_current;
    uint16_t available_min_dc_current;
    uint16_t max_dc_current;
    uint16_t min_dc_current;

    if (size < 8u) {
        return (-EINVAL);
    }

    max_dc_current = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    max_dc_current |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->max_dc_current = (int16_t)max_dc_current;
    available_max_dc_current = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    available_max_dc_current |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->available_max_dc_current = (int16_t)available_max_dc_current;
    min_dc_current = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    min_dc_current |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->min_dc_current = (int16_t)min_dc_current;
    available_min_dc_current = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    available_min_dc_current |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);
    dst_p->available_min_dc_current = (int16_t)available_min_dc_current;

    return (0);
}

int hv500_can2_map_v25_sid_hv500_min_max_dc_current_init(struct hv500_can2_map_v25_sid_hv500_min_max_dc_current_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct hv500_can2_map_v25_sid_hv500_min_max_dc_current_t));

    return 0;
}

int16_t hv500_can2_map_v25_sid_hv500_min_max_dc_current_max_dc_current_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double hv500_can2_map_v25_sid_hv500_min_max_dc_current_max_dc_current_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool hv500_can2_map_v25_sid_hv500_min_max_dc_current_max_dc_current_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 8500));
}

int16_t hv500_can2_map_v25_sid_hv500_min_max_dc_current_available_max_dc_current_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double hv500_can2_map_v25_sid_hv500_min_max_dc_current_available_max_dc_current_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool hv500_can2_map_v25_sid_hv500_min_max_dc_current_available_max_dc_current_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 8500));
}

int16_t hv500_can2_map_v25_sid_hv500_min_max_dc_current_min_dc_current_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double hv500_can2_map_v25_sid_hv500_min_max_dc_current_min_dc_current_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool hv500_can2_map_v25_sid_hv500_min_max_dc_current_min_dc_current_is_in_range(int16_t value)
{
    return ((value >= -8500) && (value <= 0));
}

int16_t hv500_can2_map_v25_sid_hv500_min_max_dc_current_available_min_dc_current_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double hv500_can2_map_v25_sid_hv500_min_max_dc_current_available_min_dc_current_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool hv500_can2_map_v25_sid_hv500_min_max_dc_current_available_min_dc_current_is_in_range(int16_t value)
{
    return ((value >= -8500) && (value <= 0));
}
