#pragma  once
#include <zephyr/device.h>
#include <zephyr/devicetree.h>
#include <zephyr/drivers/can.h>
#include <zephyr/kernel.h>
#include <zephyr/logging/log.h>
#include <zephyr/types.h>
#include <stdio.h>
#include <sys/_intsup.h>
#include <zephyr/drivers/gpio.h>
